### ISSUE TITLE
Cannot run parliament2

### ISSUE THREAD

**Issue by annegreu** [slzarate/parliament2#1]
Hi, 
I was trying to run parliament2 using docker but I get the following error:

docker run -v $ALIGNMENTS -v $PARLIAMENT_OUT dnanexus/parliament2:v0.1.11-0-gb492db6d --bam C-G0-S1.sorted.bam --bai C-G0-S1.sorted.bam.bai --fai TAIR10_chr_all.fas.fai -r TAIR10_chr_all.fas --breakdancer --cnvnator --manta --breakseq --delly_deletion --delly_insertion --delly_inversion --delly_duplication --lumpy --genotype
ERROR: An invalid (nonexistent) input file has been specified.
Traceback (most recent call last):
  File "/home/dnanexus/parliament2.py", line 80, in <module>
    main()
  File "/home/dnanexus/parliament2.py", line 76, in main
    run_parliament(args.bam, args.bai, ref_genome_name, args.fai, prefix, args.filter_short_contigs, args.breakdancer, args.breakseq, args.manta, args.cnvnator, args.lumpy, args.delly_deletion, args.delly_insertion, args.delly_inversion, args.delly_duplication, args.genotype, args.svviz, args.svviz_only_validated_candidates, args.dnanexus)
  File "/home/dnanexus/parliament2.py", line 49, in run_parliament
    subprocess.check_call(['bash', 'parliament2.sh', bam, bai, ref_genome, fai, prefix, str(filter_short_contigs), str(breakdancer), str(breakseq), str(manta), str(cnvnator), str(lumpy), str(delly_deletion), str(delly_insertion), str(delly_inversion), str(delly_duplication), str(genotype), str(svviz), str(svviz_only_validated_candidates), str(dnanexus)])
  File "/miniconda/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bash', 'parliament2.sh', '/home/dnanexus/in/C-G0-S1.sorted.bam', '/home/dnanexus/in/C-G0-S1.sorted.bam.bai', '/home/dnanexus/in/TAIR10_chr_all.fas', '/home/dnanexus/in/TAIR10_chr_all.fas.fai', 'C-G0-S1.sorted', 'False', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'False', 'False', 'False']' returned non-zero exit status 1

This is my input:
docker run -v $ALIGNMENTS -v $PARLIAMENT_OUT dnanexus/parliament2:v0.1.11-0-gb492db6d --bam C-G0-S1.sorted.bam --bai C-G0-S1.sorted.bam.bai --fai TAIR10_chr_all.fas.fai -r TAIR10_chr_all.fas --breakdancer --cnvnator --manta --breakseq --delly_deletion --delly_insertion --delly_inversion --delly_duplication --lumpy --genotype 

It seems /home/dnanexus/in/ gets added to the path of my input file. Is there a way to switch that off?

Thanks for your help!

**Comment by slzarate** [comment]
Unfortunately, at this time, there isn't a way to switch that off, as the Docker image was initially written to be compatible with the DNAnexus platform. I would like to revamp the Docker image for easier use locally, but at this time, no such feature exists.

**Comment by JiaB-He** [comment]
> Hi, I was trying to run parliament2 using docker but I get the following error:
> 
> docker run -v $ALIGNMENTS -v $PARLIAMENT_OUT dnanexus/parliament2:v0.1.11-0-gb492db6d --bam C-G0-S1.sorted.bam --bai C-G0-S1.sorted.bam.bai --fai TAIR10_chr_all.fas.fai -r TAIR10_chr_all.fas --breakdancer --cnvnator --manta --breakseq --delly_deletion --delly_insertion --delly_inversion --delly_duplication --lumpy --genotype ERROR: An invalid (nonexistent) input file has been specified. Traceback (most recent call last): File "/home/dnanexus/parliament2.py", line 80, in main() File "/home/dnanexus/parliament2.py", line 76, in main run_parliament(args.bam, args.bai, ref_genome_name, args.fai, prefix, args.filter_short_contigs, args.breakdancer, args.breakseq, args.manta, args.cnvnator, args.lumpy, args.delly_deletion, args.delly_insertion, args.delly_inversion, args.delly_duplication, args.genotype, args.svviz, args.svviz_only_validated_candidates, args.dnanexus) File "/home/dnanexus/parliament2.py", line 49, in run_parliament subprocess.check_call(['bash', 'parliament2.sh', bam, bai, ref_genome, fai, prefix, str(filter_short_contigs), str(breakdancer), str(breakseq), str(manta), str(cnvnator), str(lumpy), str(delly_deletion), str(delly_insertion), str(delly_inversion), str(delly_duplication), str(genotype), str(svviz), str(svviz_only_validated_candidates), str(dnanexus)]) File "/miniconda/lib/python2.7/subprocess.py", line 190, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '['bash', 'parliament2.sh', '/home/dnanexus/in/C-G0-S1.sorted.bam', '/home/dnanexus/in/C-G0-S1.sorted.bam.bai', '/home/dnanexus/in/TAIR10_chr_all.fas', '/home/dnanexus/in/TAIR10_chr_all.fas.fai', 'C-G0-S1.sorted', 'False', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'False', 'False', 'False']' returned non-zero exit status 1
> 
> This is my input: docker run -v $ALIGNMENTS -v $PARLIAMENT_OUT dnanexus/parliament2:v0.1.11-0-gb492db6d --bam C-G0-S1.sorted.bam --bai C-G0-S1.sorted.bam.bai --fai TAIR10_chr_all.fas.fai -r TAIR10_chr_all.fas --breakdancer --cnvnator --manta --breakseq --delly_deletion --delly_insertion --delly_inversion --delly_duplication --lumpy --genotype
> 
> It seems /home/dnanexus/in/ gets added to the path of my input file. Is there a way to switch that off?
> 
> Thanks for your help!

Hello
I encountered the same problem as you, did you solve it?
Thank you for your answer ！

**Comment by dansteiert** [comment]
you can provide full paths starting with the /home/dnanexus/in/PATH_TO_YOUR_FILE_FROM_MOUNT -> this works for me for -> but careful -> it moves my file even though it is "read-only"!

File gets moved to your mapped /home/dnanexus/in/input.bam
